version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    docker:
      - image: circleci/node:14.6-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/tmp
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: /tmp/test-results
            JEST_JUNIT_OUTPUT_NAME: unit.xml
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
      - codecov/upload:
          file: /tmp/test-results/coverage-final.json
