version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.6-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/tmp
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test:ci --coverageDirectory=/tmp/test-results/coverage
          environment:
            JEST_JUNIT_OUTPUT_DIR: /tmp/test-results
            JEST_JUNIT_OUTPUT_NAME: coverage.xml
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
