name: Release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Create version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Repository
        run: git fetch --unshallow --tags
      - name: Install Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Node Modules
        run: |
          npm install
      - name: Create Release
        run: |
          npm test
